/* eslint-disable global-require */
// type : 1. 早餐 2. 午餐 3. 晚餐  4. 下午茶
// dayoff : 1,2,3,4,5,6,7
const store = [
  {
    name: '樂華',
    location: '金城北鎮廟',
    tel: '082-333111',
    bg: require('../assets/images/food1.jpg'),
    time: '08:00 ~ 14:00',
    dayoff: '',
    type: '',
    price: '',
  },
  {
    name: '岡山羊肉',
    location: '金城東門菜市場',
    tel: '082-333111',
    bg: require('../assets/images/food2.jpg'),
    time: '08:00 ~ 14:00',
    dayoff: '',
    type: '',
    price: '',
  },
  {
    name: '福記',
    location: '金城東門菜市場',
    tel: '082-333111',
    bg: require('../assets/images/food1.jpg'),
    time: '08:00 ~ 15:00',
    dayoff: '',
    type: '',
    price: '',
  },
  {
    name: '遠來興',
    location: '金門縣金沙鎮三民路22巷11號',
    tel: '',
    bg: require('../assets/images/food1.jpg'),
    time: '05:00 ~ 13:00',
    dayoff: '',
    type: '1',
    price: '100',
  },
  {
    name: '韓式小姐',
    location: '金門縣金城鎮光前路99號',
    tel: '',
    bg: require('../assets/images/food1.jpg'),
    time: '15:30 ~ 22:30',
    dayoff: '1',
    type: '4',
    price: '100',
  },
  {
    name: '如荷咖啡',
    location: '金門縣金湖鎮環島南路四段282號',
    tel: '',
    bg: require('../assets/images/food1.jpg'),
    time: '11:00 ~ 21:00',
    dayoff: '',
    type: '2,3,4',
    price: '300',
  },
  {
    name: '月之華',
    location: '金門縣金寧鄉環島西路二段65號',
    tel: '',
    bg: require('../assets/images/food1.jpg'),
    time: '11:30 ~ 13:30 17:30 ~ 20:00',
    dayoff: '7',
    type: '2,3',
    price: '360',
  },
  {
    name: '貝雷納廚坊',
    location: '金門縣金沙鎮三民路8號',
    tel: '',
    bg: require('../assets/images/food1.jpg'),
    time: '05:30 ~ 11:00',
    dayoff: '',
    type: '1',
    price: '100',
  },
  {
    name: '關魚壽司',
    location: '金門縣金城鎮中興路161巷17號1樓',
    tel: '',
    bg: require('../assets/images/food1.jpg'),
    time: '',
    dayoff: '',
    type: '2,3',
    price: '100',
  },
  {
    name: '榕榕園',
    location: '金門縣金湖鎮黃海路7號',
    tel: '',
    bg: require('../assets/images/food1.jpg'),
    time: '',
    dayoff: '',
    type: '2,3',
    price: '100',
  },
  {
    name: '北山古寧頭老麵茶',
    location: '金門縣金寧鄉古寧頭北山',
    tel: '',
    bg: require('../assets/images/food1.jpg'),
    time: '10:00 ~ 18:00',
    dayoff: '',
    type: '2,3',
    price: '100',
  },
  {
    name: '金門第一家炸雞',
    location: '金門縣金城鎮北鎮廟左手邊上坡',
    tel: '',
    bg: require('../assets/images/food1.jpg'),
    time: '15:30 ~ 24:00',
    dayoff: '',
    type: '4',
    price: '100',
  },
  {
    name: '金許園',
    location: '金門縣金城鎮官裡53號',
    tel: '',
    bg: require('../assets/images/food1.jpg'),
    time: '',
    dayoff: '',
    type: '2,3',
    price: '300',
  },
  {
    name: '佳味小吃',
    location: '金門縣金城鎮莒光路26巷12號',
    tel: '',
    bg: require('../assets/images/food1.jpg'),
    time: '06:00 ~ 11:00',
    dayoff: '',
    type: '1',
    price: '100',
  },
  {
    name: '一世情緣美食館',
    location: '金門縣金城鎮民生路45巷22號',
    tel: '',
    bg: require('../assets/images/food1.jpg'),
    time: '',
    dayoff: '',
    type: '3',
    price: '100',
  },
  {
    name: '蜉蝣咖啡',
    location: '金門縣金城鎮富康一村6巷15號',
    tel: '',
    bg: require('../assets/images/food1.jpg'),
    time: '',
    dayoff: '',
    type: '4',
    price: '100',
  },
  {
    name: '蝸居',
    location: '金門縣金城鎮民權路122巷20號',
    tel: '',
    bg: require('../assets/images/food1.jpg'),
    time: '',
    dayoff: '',
    type: '1',
    price: '100',
  },
  {
    name: '俊輝碳烤-金城',
    location: '金門縣金城鎮民權路98號',
    tel: '',
    bg: require('../assets/images/food1.jpg'),
    time: '',
    dayoff: '',
    type: '3',
    price: '200',
  },
  {
    name: '俊輝碳烤-金湖',
    location: '金門縣金湖鎮新湖里新頭98號',
    tel: '',
    bg: require('../assets/images/food1.jpg'),
    time: '',
    dayoff: '',
    type: '3',
    price: '200',
  },
];

export default store;
